# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Exciting New Features and Enhancements
      labels:
        - feature
    - title: 🎨 UX/UI Updates
      labels:
        - design
    - title: 📚 Content Updates
      labels:
        - content
    - title: 📝 Documentation Updates
      labels:
        - documentation
    - title: 🐛 Bugs Fixed
      labels:
        - bug
    - security: 🔒 Security Updates
      labels:
        - security
    - title: 🤖 DevOps Improvements
      labels:
        - devops
    - title: 🔧 Fixes Applied
      labels:
        - maintenance
    - title: ⚙️ Behind the Scenes
      labels:
        - '*'