name: All Tests Passing

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install PostgreSQL
      run: sudo apt-get -yqq install libpq-dev

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Database Setup
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
      run: |
        bin/rails db:create db:migrate db:schema:load

    - name: Run Tests
      run: bundle exec rspec